apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
    selector:
      app: kub-example-fastapi
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80
    type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kub-example-fastapi
spec:
  replicas: 1
  selector:
      matchLabels:
        app: kub-example-fastapi
        tier: backend
      #matchExpressions:
        #- {key: app, operator: In, values: [kub-example-fastapi, backend]}
  template:
    metadata:
      labels:
        app: kub-example-fastapi
        tier: backend
    spec:
      containers:
      - name: example-fastapi
        image: thegera4/fastapi-example:latest
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10